name: Test Workflow

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Test basic functionality
      run: |
        echo "✅ Workflow is working!"
        echo "Repository: ${{ github.repository }}"
        echo "Branch: ${{ github.ref_name }}"
        echo "Commit: ${{ github.sha }}"
        
    - name: Test Go setup
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'
        
    - name: Test build
      run: |
        echo "Testing Go installation..."
        go version
        echo "Testing dependencies..."
        go mod tidy
        echo "Testing client build..."
        go build -o test_client.exe ./cmd/client
        echo "✅ Build successful!"
